export default function rankTranslate(rank) {
    if(!rank) return null
    switch(rank) {
        case "IRON_IV":
            return 1
        case "IRON_III":
            return 2
        case "IRON_II":
            return 3
        case "IRON_I":
            return 4
        case "BRONZE_IV":
            return 5
        case "BRONZE_III":
            return 6
        case "BRONZE_II":
            return 7
        case "BRONZE_I":
            return 8
        case "SILVER_IV":
            return 9
        case "SILVER_III":
            return 10
        case "SILVER_II":
            return 11
        case "SILVER_I":
            return 12
        case "GOLD_IV":
            return 13
        case "GOLD_III":
            return 14
        case "GOLD_II":
            return 15
        case "GOLD_I":
            return 16
        case "PLATINUM_IV":
            return 17
        case "PLATINUM_III":
            return 18
        case "PLATINUM_II":
            return 19
        case "PLATINUM_I":
            return 20
        case "DIAMOND_IV":
            return 21
        case "DIAMOND_III":
            return 22
        case "DIAMOND_II":
            return 23
        case "DIAMOND_I":
            return 24
        case "MASTER":
            return 25
        case "GRANDMASTER":
            return 26
        case "CHALLENGER":
            return 27
        case 1:
            return "IRON_IV"
        case 2:
            return "IRON_III"
        case 3:
            return "IRON_II"
        case 4:
            return "IRON_I"
        case 5:
            return "BRONZE_IV"
        case 6:
            return "BRONZE_III"
        case 7:
            return "BRONZE_II"
        case 8:
            return "BRONZE_I"
        case 9:
            return "SILVER_IV"
        case 10:
            return "SILVER_III"
        case 11:
            return "SILVER_II"
        case 12:
            return "SILVER_I"
        case 13:
            return "GOLD_IV"
        case 14:
            return "GOLD_III"
        case 15:
            return "GOLD_II"
        case 16:
            return "GOLD_I"
        case 17:
            return "PLATINUM_IV"
        case 18:
            return "PLATINUM_III"
        case 19:
            return "PLATINUM_II"
        case 20:
            return "PLATINUM_I"
        case 21:
            return "DIAMOND_IV"
        case 22:
            return "DIAMOND_III"
        case 23:
            return "DIAMOND_II"
        case 24:
            return "DIAMOND_I"
        case 25:
            return "MASTER"
        case 26:
            return "GRANDMASTER"
        case 27:
            return "CHALLENGER"
        default:
            return null
    }
}